### ISSUE TITLE
MiBand demo not working "GATT Error Unknown"

### ISSUE THREAD

**Issue by jakearchibald** [beaufortfrancois/sandbox#2]
<img width="452" alt="screen shot 2016-03-03 at 16 58 57" src="https://cloud.githubusercontent.com/assets/93594/13502191/cb71fc82-e161-11e5-8f79-b0259f134fc9.png">

This happens after pairing

**Comment by beaufortfrancois** [comment]
@jakearchibald  I've just pushed a [fix](https://github.com/beaufortfrancois/sandbox/commit/0e348c58615734a749f8c532cbf17c9732a15033) but I don't have my miBand to test this.
Can you let me know how it goes for you?

**Comment by jakearchibald** [comment]
Still getting the same error :(

**Comment by jakearchibald** [comment]
It fails on `characteristic.readValue()` for the steps UUID

**Comment by jakearchibald** [comment]
Hmm, it displays steps if I comment out `return miBand.pair(reset)` - so looks like the pairing is causing the problems

**Comment by jakearchibald** [comment]
I got updates working by removing all `_startNotifications` except for `STEPS_UUID`. Unfortunately I only got a few `characteristicvaluechanged`s then it stopped working. I think this is a platform bug, as I'm seeing the same with the heart rate monitor demo, and refreshing the browser doesn't fix it, getting no `characteristicvaluechanged`s now.

**Comment by jakearchibald** [comment]
https://bugs.chromium.org/p/chromium/issues/detail?id=594525

**Comment by beaufortfrancois** [comment]
Thanks @jakearchibald.
Will have a look over there.
